package org.javaavc.ffmpeg_gen.avfilter;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import org.javaavc.ffmpeg_gen.avfilter.LibavfilterLibrary.AVRational;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVFilterBufferRefVideoProps extends Structure {
	/** < image width */
	public int w;
	/** < image height */
	public int h;
	/**
	 * < sample aspect ratio<br>
	 * C type : AVRational
	 */
	public AVRational sample_aspect_ratio;
	/** < is frame interlaced */
	public int interlaced;
	/** < field order */
	public int top_field_first;
	/**
	 * @see AVPictureType<br>
	 * < picture type of the frame<br>
	 * C type : AVPictureType
	 */
	public int pict_type;
	/** < 1 -> keyframe, 0-> not */
	public int key_frame;
	/** < qp_table stride */
	public int qp_table_linesize;
	/** < qp_table size */
	public int qp_table_size;
	/**
	 * < array of Quantization Parameters<br>
	 * C type : int8_t*
	 */
	public Pointer qp_table;
	public AVFilterBufferRefVideoProps() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("w", "h", "sample_aspect_ratio", "interlaced", "top_field_first", "pict_type", "key_frame", "qp_table_linesize", "qp_table_size", "qp_table");
	}
	public static class ByReference extends AVFilterBufferRefVideoProps implements Structure.ByReference {
		
	};
	public static class ByValue extends AVFilterBufferRefVideoProps implements Structure.ByValue {
		
	};
}
