package org.javaavc.ffmpeg_gen.avfilter;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVFilterInOut extends Structure {
	/**
	 * unique name for this input/output in the list<br>
	 * C type : char*
	 */
	public Pointer name;
	/**
	 * filter context associated to this input/output<br>
	 * C type : AVFilterContext*
	 */
	public org.javaavc.ffmpeg_gen.avfilter.AVFilterContext.ByReference filter_ctx;
	/** index of the filt_ctx pad to use for linking */
	public int pad_idx;
	/**
	 * next input/input in the list, NULL if this is the last<br>
	 * C type : AVFilterInOut*
	 */
	public AVFilterInOut.ByReference next;
	public AVFilterInOut() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("name", "filter_ctx", "pad_idx", "next");
	}
	/**
	 * @param name unique name for this input/output in the list<br>
	 * C type : char*<br>
	 * @param filter_ctx filter context associated to this input/output<br>
	 * C type : AVFilterContext*<br>
	 * @param pad_idx index of the filt_ctx pad to use for linking<br>
	 * @param next next input/input in the list, NULL if this is the last<br>
	 * C type : AVFilterInOut*
	 */
	public AVFilterInOut(Pointer name, org.javaavc.ffmpeg_gen.avfilter.AVFilterContext.ByReference filter_ctx, int pad_idx, AVFilterInOut.ByReference next) {
		super();
		this.name = name;
		this.filter_ctx = filter_ctx;
		this.pad_idx = pad_idx;
		this.next = next;
	}
	public static class ByReference extends AVFilterInOut implements Structure.ByReference {
		
	};
	public static class ByValue extends AVFilterInOut implements Structure.ByValue {
		
	};
}
